# Generated by Django 3.1.7 on 2021-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
    ]
