# Generated by Django 3.1.7 on 2021-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
